# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903d8e8204ace6f15ff9b3b3104bdc52672da8032bcde552e2722ef9c7174b177fbe9eeb8bd7cac03583e6e8985871732b371bfa41a5ab67955cee38ed452660

test:
  secret_key_base: 6ac82b8a2bf94c882e1c5ea1a5acd542c344e3bf5c7f3d97f63550fa91319a8db516433fedff0ecf6acc998c4e463bf6299eeb43dfeb47cb9e95062cec82831b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
